個人イベント開催の中に文章追加しました。Personal eventadd0706
tech-training/tech-commit-doc pull request #40
Opened 2021-07-06 13:11 UTC by yukiko1026

【個人イベント開催ガイドラインのドキュメント更新内容の作成】7/6(火)実施
 Gitドキュメント更新の2回目提出のプルリクエストです。
個人イベント開催の中に文章を入力行いました。
ご確認をお願いいたします。

2021-07-07 12:51 UTC, inodev requested changes

2021-07-07 12:51 UTC, inodev commented on docs/personal-event.md
> +●趣味会（例：オンラインボードゲーム会）
[IMO]

```suggestion
- 輪読会（書籍は自分が読みたいもの）
- 意見交換会
- アイディアソン（皆でテーマに即したサービスやアプリのアイディアを考える会）
- 交流会・飲み会
- 趣味会（例：オンラインボードゲーム会）
```

ちゃんとMarkdownのリストを使っていただけると幸いです 🙏 （他のところも）

2021-07-07 12:51 UTC, inodev commented on docs/personal-event.md
> +
[IMO]
この行は無くてもいいかなと思います。

2021-07-07 12:51 UTC, inodev commented on docs/personal-event.md
> +
[IMO]
この行は無くてもいいかなと思います。

2021-07-07 12:51 UTC, inodev commented on docs/personal-event.md
> +
[IMO]
この行はなくてもいいかなと思います。

2021-07-07 12:51 UTC, inodev commented on docs/tutorial/about.md
> +個人イベント開催の約束事などについては「[個人イベント開催について](../personal-event.html)」を御覧ください。
[IMO]

```suggestion
個人イベント開催の約束事などについては「[個人イベント開催について](../personal-event)」を御覧ください。
```

他の実装を見て同じようにやりましょう 🙏

2021-07-08 07:38 UTC, yukiko1026 commented on docs/personal-event.md
> +●趣味会（例：オンラインボードゲーム会）
はい、本日修正いたしました！

2021-07-08 07:59 UTC, yukiko1026 commented on docs/tutorial/about.md
> +個人イベント開催の約束事などについては「[個人イベント開催について](../personal-event.html)」を御覧ください。
はい。
本日【../personal-event】と入力をして、ようこそTechcommitへの「個人イベント開催の約束事などについては「個人イベント開催について」を御覧ください。」より、画面遷移の確認をしたのですが「404 - Not found」と表示されてしまう状況でした。

そのため正常に画面が表示される【../personal-event.html】へ書き換えを行いました。

2021-07-18 05:52 UTC, inodev commented
#41 で対応するためこちらはクローズ

2021-07-18 05:52 UTC, closed without merging